name: Run tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:12

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container: node:12
    needs: lint

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Jest tests
        run: npm run test
